use mtg;
INSERT INTO sets (name, code) VALUES
('Aether Revolt','AER'),
('Alara Reborn','ARB'),
('Alliances','AL'),
('Amonkhet','AKH'),
('Antiquities','AQ'),
('Apocalypse','AP'),
('Arabian Nights','AN'),
('Archenemy','ARC'),
('Archenemy: Nicol Bolas','E01'),
('Avacyn Restored','AVR'),
('Battle for Zendikar','BFZ'),
('Battle Royale Box Set','BR'),
('Battlebond','BBD'),
('Beatdown Box Set','BD'),
('Betrayers of Kamigawa','BOK'),
('Born of the Gods','BNG'),
('Champions of Kamigawa','CHK'),
('Chronicles','CH'),
('Coldsnap','CS'),
('Commander','CMD'),
('Commander 2013 Edition','C13'),
('Commander 2014 Edition','C14'),
('Commander 2015 Edition','C15'),
('Commander 2016 Edition','C16'),
('Commander 2017 Edition','C17'),
('Commander 2018 Edition','C18'),
('Commander 2019 Edition','C19'),
('Commander Anthology','CMA'),
('Commander Anthology Volume II','CM2'),
('Commander''''s Arsenal','CRS'),
('Conflux','CFX'),
('Conspiracy','CNS'),
('Conspiracy: Take the Crown','CN2'),
('Dark Ascension','DKA'),
('Darksteel','DS'),
('Dissension','DIS'),
('Dominaria','DOM'),
('Dragon''s Maze','DGM'),
('Dragons of Tarkir','DTK'),
('Duel Decks Anthology, Divine vs. Demonic','ADVD'),
('Duel Decks Anthology, Elves vs. Goblins','AEVG'),
('Duel Decks Anthology, Garruk vs. Liliana','AGVL'),
('Duel Decks Anthology, Jace vs. Chandra','AJVC'),
('Duel Decks: Ajani vs. Nicol Bolas','AVB'),
('Duel Decks: Blessed vs. Cursed','BVC'),
('Duel Decks: Divine vs. Demonic','DVD'),
('Duel Decks: Elspeth vs. Kiora','EVK'),
('Duel Decks: Elspeth vs. Tezzeret','EVT'),
('Duel Decks: Elves vs. Goblins','EVG'),
('Duel Decks: Elves vs. Inventors','EVI'),
('Duel Decks: Garruk vs. Liliana','GVL'),
('Duel Decks: Heroes vs. Monsters','HVM'),
('Duel Decks: Izzet vs. Golgari','IVG'),
('Duel Decks: Jace vs. Chandra','JVC'),
('Duel Decks: Jace vs. Vraska','JVV'),
('Duel Decks: Knights vs. Dragons','KVD'),
('Duel Decks: Merfolk vs. Goblins','MVG'),
('Duel Decks: Mind vs. Might','MVM'),
('Duel Decks: Nissa vs. Ob Nixilis','NVO'),
('Duel Decks: Phyrexia vs. the Coalition','PVC'),
('Duel Decks: Sorin vs. Tibalt','SVT'),
('Duel Decks: Speed vs. Cunning','SVC'),
('Duel Decks: Venser vs. Koth','VVK'),
('Duel Decks: Zendikar vs. Eldrazi','ZVE'),
('Eighth Edition','8E'),
('Eldritch Moon','EMN'),
('Eternal Masters','EMA'),
('Eventide','EVE'),
('Exodus','EX'),
('Explorers of Ixalan','E02'),
('Fallen Empires','FE'),
('Fate Reforged','FRF'),
('Fifth Dawn','FD'),
('Fifth Edition','5E'),
('Fourth Edition','4E'),
('From the Vault: Angels','V15'),
('From the Vault: Annihilation','V14'),
('From the Vault: Dragons','V08'),
('From the Vault: Exiled','V09'),
('From the Vault: Legends','V11'),
('From the Vault: Lore','V16'),
('From the Vault: Realms','V12'),
('From the Vault: Relics','V10'),
('From the Vault: Transform','V17'),
('From the Vault: Twenty','V13'),
('Future Sight','FUT'),
('Game Night','GNT'),
('Game Night 2019','GN2'),
('Gatecrash','GTC'),
('Global Series: Jiang Yanggu and Mu Yanling','GS1'),
('Guildpact','GP'),
('Guilds of Ravnica','GRN'),
('Guilds of Ravnica Mythic Edition','MED'),
('Homelands','HL'),
('Hour of Devastation','HOU'),
('Ice Age','IA'),
('Iconic Masters','IMA'),
('Innistrad','ISD'),
('Invasion','IN'),
('Ixalan','XLN'),
('Journey into Nyx','JOU'),
('Judgment','JU'),
('Kaladesh','KLD'),
('Khans of Tarkir','KTK'),
('Legends','LG'),
('Legions','LE'),
('Limited Edition Alpha','A'),
('Limited Edition Beta','B'),
('Lorwyn','LRW'),
('Magic 2010 Core Set','M10'),
('Magic 2011 Core Set','M11'),
('Magic 2012 Core Set','M12'),
('Magic 2013 Core Set','M13'),
('Magic 2014 Core Set','M14'),
('Magic 2015 Core Set','M15'),
('Magic 2019 Core Set','M19'),
('Magic 2020 Core Set','M20'),
('Magic Origins','ORI'),
('Masterpiece Series: Amonkhet Invocations','AKHM'),
('Masterpiece Series: Kaladesh Inventions','KLDM'),
('Masters 25','A25'),
('Masters Edition','ME1'),
('Masters Edition II','ME2'),
('Masters Edition III','ME3'),
('Masters Edition IV','ME4'),
('Mercadian Masques','MM'),
('Mirage','MI'),
('Mirrodin','MR'),
('Mirrodin Besieged','MBS'),
('Modern Event Deck 2014','MD1'),
('Modern Horizons','MH1'),
('Modern Masters','MMA'),
('Modern Masters 2015 Edition','MM2'),
('Modern Masters 2017 Edition','MM3'),
('Morningtide','MOR'),
('Mystery Booster','CMB1'),
('Nemesis','NE'),
('New Phyrexia','NPH'),
('Ninth Edition','9E'),
('Oath of the Gatewatch','OGW'),
('Odyssey','OD'),
('Onslaught','ON'),
('Planar Chaos','PLC'),
('Planechase','PCH'),
('Planechase 2012 Edition','PC2'),
('Planechase Anthology','PCA'),
('Planeshift','PS'),
('Portal','PT'),
('Portal Second Age','P2'),
('Portal Three Kingdoms','P3'),
('Premium Deck Series: Fire and Lightning','PD2'),
('Premium Deck Series: Graveborn','PD3'),
('Sixth Edition','6E'),
('Zendikar','ZEN');